### ISSUE TITLE
Update Derived state

### ISSUE THREAD

**Issue by paoloricciuti** [mainmatter/sheepdog#79]
https://ember-concurrency.com/api/Task.html
```[tasklist]
### Tasks
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/80
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/81
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/82
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/83
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/84
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/85
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/86
- [ ] https://github.com/mainmatter/svelte-concurrency/issues/87
- [ ] https://github.com/mainmatter/sheepdog/issues/125
- [ ] https://github.com/mainmatter/sheepdog/issues/127
- [ ] https://github.com/mainmatter/sheepdog/issues/128
```
